import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';

// Runs as tauri.conf.json's beforeBuildCommand. Writes the git commit this
// build was made from into web/build-info.js so the running app can tell
// (by comparing against the live server's /health commit) if its bundled
// UI has gone stale relative to source — see nova-dual-repo-and-shell-skill
// memory for why this exists.

const here = dirname(fileURLToPath(import.meta.url));
const webDir = resolve(here, '..', '..', 'web');

let commit = null;
try {
  // cwd anywhere inside the repo works — git walks up to find .git, so
  // this resolves correctly whether Dashboard/ is embedded in NOVA or is
  // itself the repo root (the standalone dashboard-only repo).
  commit = execSync('git rev-parse --short HEAD', {
    cwd: here,
    stdio: ['ignore', 'pipe', 'ignore'],
  })
    .toString()
    .trim() || null;
} catch {
  commit = null;
}

const builtAt = new Date().toISOString();
const contents = `// Generated by nova-app/scripts/stamp-build.mjs at tauri build time. Do not edit or commit.\nwindow.NOVA_BUILD = ${JSON.stringify({ commit, builtAt }, null, 2)};\n`;

await writeFile(resolve(webDir, 'build-info.js'), contents, 'utf8');
console.log(`Stamped build-info.js: commit=${commit ?? 'unknown'} builtAt=${builtAt}`);
